# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadingWindow(object):
    def setupUi(self, LoadingWindow):
        LoadingWindow.setObjectName("LoadingWindow")
        LoadingWindow.resize(437, 250)
        LoadingWindow.setMinimumSize(QtCore.QSize(350, 250))
        LoadingWindow.setMaximumSize(QtCore.QSize(450, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoadingWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(LoadingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.empty_lb = QtWidgets.QLabel(self.centralwidget)
        self.empty_lb.setText("")
        self.empty_lb.setObjectName("empty_lb")
        self.horizontalLayout_2.addWidget(self.empty_lb)
        self.LogoLb = QtWidgets.QLabel(self.centralwidget)
        self.LogoLb.setMinimumSize(QtCore.QSize(100, 100))
        self.LogoLb.setMaximumSize(QtCore.QSize(100, 100))
        self.LogoLb.setText("")
        self.LogoLb.setPixmap(QtGui.QPixmap("icons/logo.png"))
        self.LogoLb.setScaledContents(True)
        self.LogoLb.setObjectName("LogoLb")
        self.horizontalLayout_2.addWidget(self.LogoLb)
        self.empty_lb_2 = QtWidgets.QLabel(self.centralwidget)
        self.empty_lb_2.setText("")
        self.empty_lb_2.setObjectName("empty_lb_2")
        self.horizontalLayout_2.addWidget(self.empty_lb_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setStyleSheet("QProgressBar#progressBar\n"
"{\n"
"      border:none;   /*无边框*/\n"
"      background:rgb(167, 169, 170);\n"
"      border-radius:5px;\n"
"      text-align:center;   /*文本的位置*/\n"
"      color: rgb(229, 229, 229);  /*文本颜色*/\n"
"}\n"
" \n"
"QProgressBar::chunk\n"
"{\n"
"      background-color:rgb(58, 154, 255);\n"
"      border-radius:4px;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(163,163,163)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.LoadingMessageLb = QtWidgets.QLabel(self.centralwidget)
        self.LoadingMessageLb.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.LoadingMessageLb.setFont(font)
        self.LoadingMessageLb.setStyleSheet("color:rgb(170, 170, 170)")
        self.LoadingMessageLb.setAlignment(QtCore.Qt.AlignCenter)
        self.LoadingMessageLb.setObjectName("LoadingMessageLb")
        self.gridLayout.addWidget(self.LoadingMessageLb, 2, 0, 1, 1)
        LoadingWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LoadingWindow)
        self.statusbar.setObjectName("statusbar")
        LoadingWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoadingWindow)
        QtCore.QMetaObject.connectSlotsByName(LoadingWindow)

    def retranslateUi(self, LoadingWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadingWindow.setWindowTitle(_translate("LoadingWindow", "AutoMeeting"))
        self.label.setText(_translate("LoadingWindow", "Tencent-AutoMeeting"))
        self.LoadingMessageLb.setText(_translate("LoadingWindow", "chromedriver更新检查中..."))
